# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/universal9810-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter crownlte star2lte starlte,$(TARGET_DEVICE)),)

endif
